spring:
  config:
    import: "optional:classpath:application-secret.yml"
  profiles:
    active: deployment
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update
openweatherapi:
  config:
    import: "optional:classpath:application-secret.yml"
  api:
    base-url: https://api.openweathermap.org/data/2.5
